### ISSUE TITLE
Issue with loading data into memory after converting Pygeode dataset to Xarray detaset

### ISSUE THREAD

**Issue by Vorticity0123** [pygeode/pygeode#125] opened 2019-08-28 22:53 UTC
Here's the problem: after converting a simple Pygeode dataset to a simple Xarray dataset, the variables thereof cannot be loaded into memory. The Xarray object can be printed, but when attempting to get the variables into memory by typing the keyword '.values' behind the variable listed, an error is returned. 

A first hunch is that this issue might be related to the Pygeode-Xarray converter being designed for older versions of Xarray, Dask or Pygeode?

For reference, I am using Xarray version 0.12.1, and Dask version 2.3.0

Here is a minimal working example to get the Traceback (making use of tutorial data from Pygeode):

`import pygeode as pyg`

`import pygeode.ext_xarray as pyg_xr`

`import xarray as xr`

`from pygeode.tutorial import t1`

`t1_xr = pyg_xr.to_xarray(t1)`

`print(t1_xr.Temp.values)`

The error returned is the following:

`KeyError: ('Temp-abc3133b89cab2145b41664d2322bb64', 0, 0)`

**Comment by neishm** [comment] 2019-08-29 15:46
Thanks for the bug report, @Vorticity0123.  I can reproduce the error in my environment.  Looks like a stray `map` iterator wasn't wrapped in a `list` before using it, and was causing problems when iterated over multiple times.  It worked in Python 2.7 (where `map` returns a `list` object by default), but was overlooked during the Python3 migration.  I'll push a fix momentarily.

**Comment by neishm** [comment] 2019-08-29 17:45
Should be fixed in the `release-1.3` branch now...

**Closed** 2019-10-02 21:45 UTC
